[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'runtime dein/onedark.vim'

[[plugins]]
repo = 'watcol/onelight.vim'
hook_add = 'runtime dein/onelight.vim'

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = 'cohama/lexima.vim'

hook_add = 'runtime dein/lexima.vim'

[[plugins]]
repo = 'lambdalisue/suda.vim'

[[plugins]]
repo = 'lambdalisue/edita.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'markonm/traces.vim'
hook_add = 'runtime dein/traces.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime dein/fzf.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'skanehira/gh.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'runtime dein/gitgutter.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = 'runtime dein/vsnip.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'runtime dein/lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = [ 'vim-lsp' ]
hook_add = 'runtime dein/lsp-settings.vim'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = 'runtime dein/vista.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = 'runtime dein/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
hook_add = 'runtime dein/asyncomp-file.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = [ 'asyncomplete.vim', 'vim-lsp' ]

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [ 'nerdfont.vim', 'gina.vim', 'vim-gitgutter', 'vim-lsp' ]
hook_add = 'runtime dein/lightline.vim'

[[plugins]]
repo = 'watcol/lightline-lsp'
depends = [ 'lightline.vim', 'vim-lsp' ]
hook_add = 'runtime dein/lightline-lsp.vim'
