# Plugin Manager
[[plugins]]
repo = 'Shougo/dein.vim'


# Colorschemes
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'runtime dein/onedark.vim'

[[plugins]]
repo = 'watcol/onelight.vim'
hook_add = 'runtime dein/onelight.vim'


# File Read/Write Extensions
[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = 'watcol/edita.vim'


# Editor Extensions
[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = 'runtime dein/lexima.vim'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'markonm/traces.vim'
hook_add = 'runtime dein/traces.vim'


# Fuzzy Finder
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime dein/fzf.vim'


# External Integrations
[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'runtime dein/gitgutter.vim'


# Snippets
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = 'runtime dein/vsnip.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'runtime dein/lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = [ 'vim-lsp' ]
hook_add = 'runtime dein/lsp-settings.vim'


# Completions
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = 'runtime dein/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
hook_add = 'runtime dein/asyncomp-file.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = [ 'asyncomplete.vim', 'vim-lsp' ]


# Statusline
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [ 'nerdfont.vim', 'gina.vim', 'vim-gitgutter', 'vim-lsp' ]
hook_add = 'runtime dein/lightline.vim'

[[plugins]]
repo = 'watcol/lightline-lsp'
depends = [ 'lightline.vim', 'vim-lsp' ]
hook_add = 'runtime dein/lightline-lsp.vim'
