[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'watcol/onelight.vim'
# hook_add = "runtime plugins/onelight.vim"

[[plugins]]
repo = 'ayu-theme/ayu-vim'
[[plugins]]
repo = 'mhartington/oceanic-next'
[[plugins]]
repo = 'sainnhe/edge'
[[plugins]]
repo = 'romgrk/github-light.vim'

[[plugins]]
repo = 'watcol/palette.vim'
hook_add = "runtime plugins/palette.vim"

[[plugins]]
repo = 'andymass/vim-matchup'
hook_add = "runtime plugins/matchup.vim"

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user']
hook_add = "runtime plugins/surround.lua"

[[plugins]]
repo = 'kwkarlwang/bufresize.nvim'
hook_add = "runtime plugins/bufresize.lua"

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = "runtime plugins/vsnip.vim"

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = ['vim-vsnip', 'ddc.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime plugins/fzf.vim'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
hook_add = "runtime plugins/galaxyline.lua"

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'jose-elias-alvarez/buftabline.nvim'
depends = ['nvim-web-devicons']
hook_add = "runtime plugins/buftabline.lua"

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['plenary.nvim']
hook_add = "runtime plugins/gitsigns.lua"

[[plugins]]
repo = 'Xuyuanp/scrollbar.nvim'
hook_add = "runtime plugins/scrollbar.vim"

[[plugins]]
repo = 'phaazon/hop.nvim'
hook_add = "runtime plugins/hop.lua"

[[plugins]]
repo = 'monaqa/dial.nvim'
hook_add = "runtime plugins/dial.lua"

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = "runtime plugins/lsp.vim"

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
hook_add = "runtime plugins/ddc.lua"

[[plugins]]
repo = 'Shougo/pum.vim'

[[multiple_plugins]]
plugins = [ 'ddc.vim', 'pum.vim', 'vim-vsnip', 'lexima.vim' ]
hook_add = "runtime plugins/ddc-pum.vim"

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
depends = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-file'
depends = ['ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-registers-words'
depends = ['ddc.vim']

[[plugins]]
repo = 'gamoutatsumi/ddc-emoji'
depends = ['ddc.vim']

[[plugins]]
repo = 'shun/ddc-vim-lsp'
depends = ['ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['ddc.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']
hook_add = "runtime plugins/skkeleton.vim"

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
