[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['python']
depends = ['deoplete.nvim']
hook_add = 'runtime dein/deoplete-jedi.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
hook_add = 'runtime dein/racer.vim'

[[plugins]]
repo = 'vim-crystal/vim-crystal'
on_ft = ['crystal']
