[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['python']
depends = ['deoplete.nvim']
hook_add = 'runtime dein/deoplete-jedi.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
hook_add = 'runtime dein/racer.vim'

[[plugins]]
repo = 'tokorom/vim-review'
on_ft = ['review']
