[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'watcol/onelight.vim'
hook_add = "runtime plugins/onelight.vim"

[[plugins]]
repo = 'andymass/vim-matchup'
hook_add = "runtime plugins/matchup.vim"

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = [ 'vim-operator-user' ]
hook_add = "runtime plugins/surround.lua"

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = "runtime plugins/vsnip.vim"

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = [ 'vim-vsnip', 'ddc.vim' ]

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = 'runtime plugins/fzf.vim'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
hook_add = "runtime plugins/galaxyline.lua"

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_add = "runtime plugins/bufferline.lua"

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = [ 'plenary.nvim' ]
hook_add = "runtime plugins/gitsigns.lua"

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = "runtime plugins/lsp.vim"

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = [ 'denops.vim' ]
hook_add = "runtime plugins/ddc.lua"

[[plugins]]
repo = 'Shougo/ddc-around'
depends = [ 'ddc.vim' ]

[[plugins]]
repo = 'shun/ddc-vim-lsp'
depends = [ 'ddc.vim' ]

[[plugins]]
repo = 'matsui54/ddc-matcher_fuzzy'
depends = [ 'ddc.vim' ]

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
depends = [ 'ddc.vim' ]

[[plugins]]
repo = 'kuuote/denops-skkeleton.vim'
depends = [ 'denops.vim' ]
hook_add = "runtime plugins/skkeleton.vim"

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = [ 'denops.vim' ]
