[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'runtime dein/onedark.vim'

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'runtime dein/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = [ 'fern.vim' ]

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'runtime dein/gitgutter.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [ 'nerdfont.vim', 'ale', 'gina.vim', 'vim-gitgutter' ]
hook_add = 'runtime dein/lightline.vim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'runtime dein/ale.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = [ 'lightline.vim', 'ale' ]
hook_add = 'runtime dein/lightline-ale.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'runtime dein/deoplete.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']

[[plugins]]
repo = 'tpope/vim-commentary'
