[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = ['DeinUpdate']

[[plugins]]
repo = 'tokorom/vim-review'
on_ft = ['review']

[[plugins]]
repo = 'gutenye/json5.vim'
on_ft = ['json5']

[[plugins]]
repo = 'lambdalisue/suda.vim'
on_cmd = ['SudaRead', 'SudaWrite']

[[plugins]]
repo = "kat0h/bufpreview.vim"
on_ft = ['markdown']
depends = ['denops.vim']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'evanleck/vim-svelte'
on_ft = ['svelte']

[[plugins]]
repo = 'mhinz/vim-sayonara'
on_cmd = ['Sayonara', 'Sayonara!']
hook_add = "runtime plugins/sayonara.vim"

[[plugins]]
repo = 'p00f/godbolt.nvim'
on_cmd = ['Godbolt', 'GodboltCompiler']
hook_post_source = 'runtime plugins/godbolt.lua'
