[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'runtime dein/lightline.vim'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'runtime dein/ale.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = [ 'lightline.vim', 'ale' ]
hook_add = 'runtime dein/lightline-ale.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'runtime dein/deoplete.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'plasticboy/vim-markdown'
