[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'runtime dein/onedark.vim'

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'runtime dein/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = [ 'fern.vim' ]

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = "runtime dein/fern-nerdfont.vim"

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'runtime dein/gitgutter.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'runtime dein/lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = [ 'vim-lsp' ]

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'runtime dein/deoplete.vim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = [ 'deoplete.nvim', 'vim-lsp-settings' ]

[[plugins]]
repo = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [ 'nerdfont.vim', 'gina.vim', 'vim-gitgutter', 'vim-lsp' ]
hook_add = 'runtime dein/lightline.vim'

[[plugins]]
repo = 'tpope/vim-commentary'
