[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'runtime dein/dein.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'runtime dein/onedark.vim'

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'runtime dein/gitgutter.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'runtime dein/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = [ 'fern.vim' ]

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = "runtime dein/fern-nerdfont.vim"

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'runtime dein/lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = [ 'vim-lsp' ]

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = 'runtime dein/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
hook_add = 'runtime dein/asyncomp-file.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = [ 'asyncomplete.vim', 'vim-lsp' ]

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [ 'nerdfont.vim', 'gina.vim', 'vim-gitgutter', 'vim-lsp' ]
hook_add = 'runtime dein/lightline.vim'

[[plugins]]
repo = 'watcol/lightline-lsp'
depends = [ 'lightline.vim', 'vim-lsp' ]
hook_add = 'runtime dein/lightline-lsp.vim'
